from typing import Any, Awaitable, Callable

class BaseHTTPMiddleware:
    def __init__(self, app: Any) -> None: ...
    async def dispatch(self, request: Any, call_next: Callable[[Any], Awaitable[Any]]) -> Any: ...
